### PR TITLE
DNN-22051 Site Setting - Site behavior - Cancel functionality is not working

### LINKED ISSUE #152: Site Setting - Site behavior - Cancel functionality is not working as expected
## Step to reproduce

- Navigate to `Site Settings > Site behaviour` 
- Make a note of values displayed - all of them. 
- Update the values to all the dropdown. 
- Click on `Cancel`
- In confirmation popup, click `Yes`

## Current behavior

Updated values are retained

## Expected behavior

Updated values should NOT be retained - Updated values should get replaced with original values.

### PR DESCRIPTION
**Pull request by mikebigun**
fixes #152

### Problem:
Persona Bar -> Site Settings -> Site Behavior
Change the values in all dropdowns, click Cancel. Values are not restored to initial ones.

### Rootcause:
Page Picker component is used to select page objects. On a cancel, component accepts default page id ([integer value](https://github.com/dnnsoftware/Dnn.React.Common/blob/173fb4f2cf9be9bff6309ef2c1470092887a921f/PagePicker/src/PagePicker.jsx#L667)) and gets list of available tab id's from API. Tab id's obtained from API are string ones. Due to type mismatching and strict comparison '===' in many places application unable to find default tab id form the available tab list.

### Solution:
Need to make sure types are matched. Once tab id's converted to integer, cancel functionality works as expected.

### CODE REVIEW

**Comment by mitchelsellers** [comment]
@valadas Any idea if we need this yet?

**Comment by valadas** [comment]
@mitchelsellers Although the changes look good to me, there is no way to really test this PR until the SiteSettings module is finished and I would like to do proper testing before merging it. So I took note of this PR on the excel worksheet for the PB modules and will review after testing properly. Also, not sure why, it says there are merge conflicts but I cannot see the conflicts, do you need write access to view the conflicts?

**Comment by valadas** [comment]
And one more thing, cancel works fine in the Pages module for the PagePicker, so I would like to compare how it is used in both modules (when SiteSettings is done) just to make sure we don't do a fix in a Common component that would fix it for one module but break it for others.

**Comment by valadas** [comment]
Ok, I have been trying to fix the merge conflict without success for quite some time. Finally understood, the file was renamed from PagePicker.jsx to index.jsx that is why. I am submitting a new PR with the same change that should replace this one.

**Comment by valadas** [comment]
Closing this for the replacement #191

**Pull request closed without merging**
