### PR TITLE
Limits react-portal-tooltip to v2.3.0

### LINKED ISSUE #182: Tooltip with info throws an error
## Describe the bug
When the tooltip component is used with info, it produces an error.

## To Reproduce
1. Clone this repo
2. Run yarn storybook
3. Open the storybood and look at the last Tootip story

## Expected behavior
Should not throw an error

## Screenshots
image

## Additional context
* This prevents the Security module from working at the moment
* I am working on this

### PR DESCRIPTION
**Pull request by valadas**
The latest react-portal-tooltip version has an issue with the latest React version. This PR limits it to the latest compatible verion. Fixes errors with tooltips and allows the Security module (and probably other modules) to not fail because of this bug.

closes #182

### CODE REVIEW

**Comment by valadas** [comment]
@mtrutledge Any oppinion on this workaround? Have a better idea on this or my solution makes sense for now?

**Comment by valadas** [comment]
Also if we can merge those 2 PRs on common, it would help with this module since I think it is affected by those two issues:

https://github.com/dnnsoftware/Dnn.React.Common/pull/183

https://github.com/dnnsoftware/Dnn.React.Common/pull/180

**Comment by ohine** [comment]
@valadas can you take a look at the conflict?

**Comment by valadas** [comment]
Oh, it is the minified result of the build, that will be re-generated by CI, should not even be tracked in my opinion... I think I can just remove it, hold on, I will try

**Comment by valadas** [comment]
Hmm, I deleted the file and pushed but it still sees that as a difference, not sure how to correct that. @ohine any advice? or you just cherry-pick it?

**Comment by ohine** [comment]
That's weird your delete didn't fix it. Sure thing, I nuke it and merge shortly. Thanks for giving it a try!

**Comment by valadas** [comment]
Yeah, if it existed before the PR and I delete it, it is still seen as a change, Ideally I should have just not included in the the commit, but not sure how to undo that.

**Comment by valadas** [comment]
I think we should delete the bundles on all those modules and add those filenames in the gitignore file. It will prevent those merge conflicts and the CI builds them anyway. Do you agree @mtrutledge  ?

**Comment by valadas** [comment]
Please do not merge yet. Looks like that bug got fixed in their latest release. I will give it a try and submit another PR if it works...

**Comment by daguiler** [comment]
Instead of deleting the file, try reverting all changes to that file in your PR @valadas, that way it will no longer cause any conflicts. And then create a new PR to remove the file.

**Comment by valadas** [comment]
Hmm, strange I commented this yesterday but it did not save. Please do not merge this, the issue might have been fixed in their latest release and this workaround not needed. Testing now, will closes if tests are conclusive.

**Comment by valadas** [comment]
Replaced by #184 I tested their new release and it works fine now, so the new solution is to upgrade instead of limit to an older version

**Pull request closed without merging**
