### PR TITLE
Fixes the invisible page pickers

### LINKED ISSUE #220: Page picker not showing
## Describe the bug
https://github.com/dnnsoftware/Dnn.React.Common/pull/218/files appears to have been done only for the dropdowns in the permission grid. The page pickers elsewhere no longer show after that PR.

## To Reproduce
1. Get this RC build https://dev.azure.com/dotnet/DNN/_build/results?buildId=9554
2. Try to use page pickers in the pages module (parent page) or in Security, redirect after login
3. Notice the page picker does not show.

## Expected behavior
Page picker should show

## Additional context
It is just a Css issue, the other pull request is ok but did not fix all the page pickers.
I am submitting another PR in a few minutes...

### PR DESCRIPTION
**Pull request by valadas**
The previous PR #218 for this was done on a file that only affected the permission grid, this one fixes the issue on all page pickers.

Closes #220

### CODE REVIEW

**Comment by valadas** [comment]
Also, I am not sure if #218 is required or not. @mtrutledge was that an error in the file it is implemented on or was that to fix another slightly different issue?

**Comment by mitchelsellers** [comment]
@valadas Can you confirm if this is still needed

**Comment by mtrutledge** [comment]
@valadas #217 was for the permission grid and was a style change in that component. The bottom borders were not showing.

**Comment by valadas** [comment]
Thanks guys, sorry I was not around much this past few days to reply...

**Pull request merged**
