### PR TITLE
Pull Request to fix Issue 155

### LINKED ISSUE #155: Restructure this project to use a single package mgt
## Is your feature request related to a problem?
Discussion: https://github.com/dnnsoftware/Dnn.React.Common/issues/154

## Describe the solution you'd like
We'll be creating a single bundle of these components as a single package which should make this project manageable. The goal is to get this done before the release of DNN 9.3.0.

### PR DESCRIPTION
**Pull request by mtrutledge**
Fixes #155

We have moved every component into the src directory. We then use webpack to create a dist folder with the svg icons and a dnn-common-react.js file.

Publishing has changed to use npmjs instead of myget. This will be published to the @dnnsoftware scope.
To Build call BuildAll.ps1
I am not sure how to publish to npmjs from Azure DevOps. Usually you do a npm addUser command and then you can publish to npmjs. The user that publishes the package needs to be a member of the dnnsoftware scope on npmjs. I can add users to that scope. There is a PublishAll.ps1 script. There are two projects to publish the main components and then the WebpackExternals.

### CODE REVIEW

**Comment by nvisionative** [comment]
Epic contribution @mtrutledge - thank you so much!

**Comment by CBPSC** [comment]
Yes, you da man Matt... thanks for all your hard work, time, and effort to make this happen!

**Comment by mtrutledge** [comment]
Now I need to start looking at the Dnn.AdminExperience project to see what needs to be updated. I have already added an issue on that repo.

**Comment by ohine** [comment]
I’ll get this merged and published tonight.

**Comment by mtrutledge** [comment]
I did find one issue with my Webpack externals config. Working on that now

**Comment by mtrutledge** [comment]
Ok should be good now with the webpack error

**Comment by mtrutledge** [comment]
Ok Oliver. I think I have all my small issues worked out.

**Pull request merged**
