### PR TITLE
Issue 164 - Add stories for TextOverflowWrapper

### LINKED ISSUE #164: Adding Story Books for TextOverflowWrapper
Currently, there are a few components that do have story books. I am opening this issue so I can add stories to those components.  This will hopefully reveal some bugs as well.

### PR DESCRIPTION
**Pull request by mtrutledge**
Fixes #164 

Adds stories for the textOverflowWrapper component and fixes a getClientRect javascript error.

### CODE REVIEW

**Comment by bdukes** [comment]
@mtrutledge I just submitted #168 which should fix the build issue, looks like your commit to fix that issue had some other stuff in there, too, not sure if we need to keep any of that or not.

**Comment by mtrutledge** [comment]
ooo looks like I pushed up a couple of the bug changes I was working on as well. Be good if we could keep them.

**Comment by bdukes** [comment]
My fix was just running `yarn upgrade`, do you think we should just take your fix and ignore mine?

**Comment by mtrutledge** [comment]
I updated to babel 7 and removed nom-run-all which was causing the error and we dont use that package any more. Lets take mine.

**Pull request merged**
